<!-- page title end-->
<link href="assets/css/styles.css" rel="stylesheet"/>
</head>
<body><div id="page" class="container">
    <header>
        <h1>Arrow Photography</h1>
        <nav>
            <ul>
                <li><a href="index.php">Home</a></li>
                <li><a href="about.php">About</a></li>
                <li><a href="services/index.php">Services</a></li>
                <li><a href="Contact.php">Contact</a></li>
            </ul>
        </nav>
    </header>
    <div id="content" class="container">
        <!--content start-->